добавила дз 3,6,7,8 урок. Ответы на вопросы (не полностью)
Maximumstart-initial-course/olga-b6-001 pull request #4
Opened 2019-01-16 16:35 UTC by OlgaD86

2019-01-30 19:25 UTC, sawex requested changes
Третья домашка: 
>Все хорошо;

Шестая:
> Контент должен быть на всю ширину страницы, сейчас есть отступы со всех сторон;

Седьмая: 
> Нужно сделать так, как мы делали на занятии, чтобы выглядела точно так же как в задании и с использованием :nth-child;
> В css-нике не должно быть вложенности больше трех элементов (сейчас 4: ".parent .child a img");

Восьмая: 
> Тоже есть вложенность больше трех в css;
> Необязательно, но неплохо было бы задать картинкам object-fit: cover, чтобы закрепить как это свойство работает;
> Было бы не плохо использовать :nth-child и в целом можно выполнить это задание можно было выполнить чуть проще, вот код: 
```
<body>
	<div class="grid">
		<a href="1300x550.png"><img src="1300x550.png" alt="1300x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="550x1100.png"><img src="550x1100.png" alt="550x1100"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
		<a href="1100x550.png"><img src="1100x550.png" alt="1100x550"></a>
	</div>

	<style>
		.grid a {margin: 5px;}
		.grid a img {
			width: 100%;
			height: 100%;
			object-fit: cover;
		} 

		.grid {
			display: grid;
			grid-template-columns: repeat(5, 1fr);
			grid-template-rows: repeat(3, 200px);
			grid-template-areas: "first first centEl . ."
							 	 ". . centEl . ."
							 	 ". . centEl . .";
		}
		.grid a:nth-child(6) {grid-area: centEl;}
		.grid a:nth-child(1) {grid-area: first;}
	</style>
</body>
```
> Сделать страничку блога.

**Ответы на вопросы**
Третья:
> Все хорошо;

Четвертая: 
> Все хорошо;

Пятая: 
> Нужно сделать

Седьмая: 
> По поводу первого вопроса, ответ верный, единственное, что было бы корректнее ответить, что свойство "display" меняет не тип элемента, а тип отображения элемента;
> Последний вопрос: нет ответа на вторую часть (как выравнять строчный элемент по центру);

Восьмая: 
> Все хорошо

Девятая: 
> Ответить про float'ы;

2019-02-18 23:55 UTC, OlgaD86 commented
Вопросы: 
Восьмая домашка, блог:
Как добавить (подключить) иконки Font Awesome?

Выпускной проект:
1. Checkbox. На макете сами окошечки, где ставятся галочки без рамки. Как это сделать?
2. Select. Как правильно сделать надпись "Select your location"?
   И как сделать вместо черной стрелочки (которая отвечает за раскрывание списка), ту, которая на макете?
3. Separator. Разделительные линии у секций. Я их поставила на места, но не уверена, что правильно.

2019-02-20 13:17 UTC, sawex commented
1. По вопросу с иконочными шрифтами. Нужно зайти на сайт FA ( https://fontawesome.com/ ) -> start using free -> там будет link, который нужно вставить в head html-ника. После этого на сайте в строке поиска найти нужную иконку (например, по запросу facebook), кликнуть на нее и там вверху появится тег с уже готовыми прописанными классами (<i class="fab fa-facebook-f"></i>). Его нужно просто вставить туда, где должна быть эта иконка и все, иконка подтянется.

2. Чекбоксы. Советую посмотреть последнее видео Вадима Макеева, он как раз очень подробно и на примере рассказывает об этом ( https://youtu.be/E6kLaaQFctU ). Лучше всего это будет сделать не картиночками, а, как он приводит тоже пример, на чистом CSS-е. Вместо галочки по клику можно сделать, например, просто залитый черным цветом квадрат с белой обводкой. 

3. Что касается селекта, то он, как и чекбоксы из коробки не кастомизируется, к сожалению, поэтому нужно к селекту привязывать лэйбл. Сам лэйбл стилизовать так, как на макете и позиционировать его на то место, где должен быть селект (соответственно и надпись тоже будет в лэйбле). Селекту же задавать opacity: 0. Он как бы, по факту, будет на странице, но будет невидимым. Кликать мы будем, в таком случае, на лейбл, а открываться будет селект. Что касается стрелочки, то к тому же лэйблу через псевдоэлемент ::after задать картинку со стрелкой и спозиционировать ее на нужное место.

4. Что касается разделителей, то, в принципе, можно просто в фотошопе через ctrl выбрать сразу картинку и эту полоску и попросту скачать их одной цельной картинкой и вставить. Но так как ты сделала тоже правильно, так что пусть остается как есть, не стоит особо заострять на них внимание :)

5. Я еще просмотрю макет и напишу либо сюда, либо в вайбер. Там нужно будет немного подправить стили у body, сделать wrapper и еще по мелочи разного. Но глобально все выглядит очень даже хорошо.

2019-02-20 14:00 UTC, sawex commented
Что поправить в макете.
1. Тегу тайтл дать название (название макета, например).
2. Подключить фавиконку.
3. У body в стилях мы прописываем только марджин и паддинг 0, ширину мы не задаем. Задний фон должен быть на всю страницу. А вот для враппера уже стоит задать ширину, при чем по контентной зоне, и марджин 0 авто.
4. На кнопку search нужен cursor: pointer, а то не сразу понятно, что на нее можно нажать.
5. В секции цвет шрифта, кажется, не черным должен быть.
6. Все в той же секции синюю полоску под словом Digital лучше наверстать руками (например обыкновенный div или span застилизовать). Это, во-первых, будет занимать меньше памяти, а во-вторых, скринридер не будет это читать как картинку.
7. В принципе у тегов img не прописаны альты, нужно прописать, даже если это обычный разделитель секции.
8. В футере конверт отлетает от текста. top: 2px должно вылечить это.
9. Цвет шрифта в футере так же, вроде бы, должен быть сероватым.
10. Стараемся максимально использовать флексы. Если сделать враппер для хэдера по контентной зоне, то не будет необходимости в пугающих значениях "padding: 85px 150px 0 168px;" для навигиции :)
11. В целом, если есть где-то возможность не использовать фиксированные значение width и heigth, а также марджинов и паддингов, а есть возможность сделать на флексах, то делаем на флексах.

Пока это вроде бы все, что попалось на глаза, что нужно подправить :)

2019-02-25 11:37 UTC, OlgaD86 commented
Подскажи, пожалуйста, как в блоге (д.р. 8) сделать черту над заголовками в правом меню при наведении мыши?

2019-02-25 20:58 UTC, sawex commented
В этой домашке достаточно просто визуально сделать такую полосу. 
Можно просто вложить див в див, обоим задать размеры и цвет и через абсолютное позиционирование реализовать. 
А так, полагаю, что это вообще задумывалось как слайдер (или что-то подобное) и полоска будет уезжать вслед за каким-то контентом. Либо это просто такая красиво задуманная дизайнерская фича. То есть, в любом случае, это не при наведении полоска должна пояляться, она фиксированная.

2019-02-27 23:54 UTC, OlgaD86 commented
Поправила макет по твоим пунктам.
Мои вопросы:
1. Не поняла как top должен был вылечить конвертик в address , вылечила флэксами и right.
2. По чекбоксам. Посмотрела видео. Не добавляла span как там предлагается (вернее добавила, и с ними такой же вопрос возник, вернулась к первоначальному варианту), а задавала квадрат в самом input. Заливка черным делается, но если выбрать один из чек-боксов и нажать например на select, выбор пропадает. Это ж не правильно?
3. Select. Добавила к нему Label. А как сделать, чтобы когда выбираешь город он отображался в строке? Т.к. select невидимый, и текст выбранный не показывается.
4. Разделители. Сделала просто div-ами, а в css добавила фон - картинку разделителя. И чтобы она на всю ширину была - повторением. Справа не очень красиво - как обрезанная - как исправить?

2019-02-28 12:17 UTC, sawex commented
1. Можно было просто затать топ 2 пикселя самому конверту и он встал бы на место, но и флексами тоже хорошо. Единственное, как по мне, лучше было бы задать left: 0, а не right 180px, чтобы не было таких больших значений, но в конкретоном случае это уже вкусовщина (но, если в блок adress добавить еще какой-то контент и блок станет шире, то, соответственно, и конверт тоже уедет, про это нужно тоже помнить; с лефт 0 он всегда будет прикреплен к левой части блочка).
![image](https://user-images.githubusercontent.com/34552809/53564840-94bfae80-3b60-11e9-82f6-cb41c291f87e.png)

2. Черным у тебя квадрат заливается и пропадат не потому, что он "чекнут", а потому, что он в фокусе (если табом проклацать до чекбоксов, то они тоже поочереди зальются), чтобы обозначить, что именно этот чексокс выбран, нужен псевдокласс :checked (хотя и :focus тут тоже в тему, хорошая практика). Глянь нашу лекцию по псевдоклассам и просто попробуй разобраться что эти два псевдокласса делают и зачем они нужны. Или в ролике у Макеева, там где он использует :checked и селектор, что он называет "однголазой совой" (если не получится разобраться самой, то пиши. Я напишу с примерами как это сделать 😃 ).

3. Тут мне нужно будет сейчас разобраться в коде и самому попробовать несколько вариантов. Как найду самый подходящий - расскажу.

4. ``` background-size: cover ```

2019-03-01 14:40 UTC, sawex commented
![default](https://user-images.githubusercontent.com/34552809/53644854-3f5ace80-3c40-11e9-95c2-832fc3e33263.png)
У этого элемента нужно переделать позиционирование, т.к. при изменение размеров экрана вот такое происходит.
И на лейблы у инпутов тоже было бы круто сделать курсор поинтер.

Все остальное вроде бы хорошо :)

2019-03-06 10:06 UTC, merged